Repository Kernel360/hackerthon1-Orury, pull requests merged in 2023-10, with the labels that each got.

#5 [Chore] yml 설정
  orury/build/resources/main/application.yml
  orury/src/main/resources/application.properties
  orury/src/main/resources/application.yml
Labels: CHORE, 🧑‍💻 이종찬

#8 Chore/#7 jpa setting
  .idea/workspace.xml
  orury/.gradle/8.3/executionHistory/executionHistory.bin
  orury/.gradle/8.3/executionHistory/executionHistory.lock
  orury/.gradle/8.3/fileHashes/fileHashes.bin
  orury/.gradle/8.3/fileHashes/fileHashes.lock
  orury/.gradle/8.3/fileHashes/resourceHashesCache.bin
  orury/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  orury/.gradle/buildOutputCleanup/outputFiles.bin
  orury/build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig.class.uniqueId0
  orury/build/tmp/compileJava/previous-compilation-data.bin
  orury/src/main/java/org/kernel360/orury/board/comment/domain/Comment.java
  orury/src/main/java/org/kernel360/orury/board/comment/domain/CommentLike.java
  orury/src/main/java/org/kernel360/orury/board/comment/repository/CommentLikeRepository.java
  orury/src/main/java/org/kernel360/orury/board/comment/repository/CommentRepository.java
  orury/src/main/java/org/kernel360/orury/board/comment/service/CommentService.java
  orury/src/main/java/org/kernel360/orury/board/post/domain/Post.java
  orury/src/main/java/org/kernel360/orury/board/post/domain/PostLike.java
  orury/src/main/java/org/kernel360/orury/board/post/repository/PostLikeRepository.java
  orury/src/main/java/org/kernel360/orury/board/post/repository/PostRepository.java
  orury/src/main/java/org/kernel360/orury/board/post/service/PostService.java
  orury/src/main/java/org/kernel360/orury/global/domain/BaseEntity.java
  orury/src/main/java/org/kernel360/orury/global/security/SecurityConfig.java
  orury/src/main/java/org/kernel360/orury/user/domain/UserAccount.java
  orury/src/main/java/org/kernel360/orury/user/repository/UserAccountRepository.java
  orury/src/main/java/org/kernel360/orury/user/service/UserAccountService.java
Labels: CHORE, 🧑‍💻 이종찬

#13 Feature/#11 user
  orury/src/main/java/org/kernel360/orury/global/controller/MainController.java
  orury/src/main/java/org/kernel360/orury/global/security/JpaConfig.java
  orury/src/main/java/org/kernel360/orury/global/security/Principal.java
  orury/src/main/java/org/kernel360/orury/global/security/SecurityConfig.java
  orury/src/main/java/org/kernel360/orury/user/domain/UserAccount.java
  orury/src/main/java/org/kernel360/orury/user/dto/UserAccountDto.java
  orury/src/main/java/org/kernel360/orury/user/repository/UserAccountRepository.java
  orury/src/main/java/org/kernel360/orury/user/service/UserAccountService.java
  orury/src/main/resources/application.yml
  orury/src/test/java/org/kernel360/orury/global/security/SecurityConfigTest.java
  orury/src/test/java/org/kernel360/orury/user/service/UserAccountServiceTest.java
Labels: ❌ FIX, 🔥 FEATURE, 🧑‍💻 이종찬

#14 Feat: "게시글 상세 조회 기능 구현"
  orury/src/main/java/org/kernel360/orury/board/comment/repository/CommentRepository.java
  orury/src/main/java/org/kernel360/orury/board/post/controller/PostController.java
  orury/src/main/java/org/kernel360/orury/board/post/service/PostService.java
  orury/src/main/resources/templates/PostDetail.html
Labels: 🔥 FEATURE, 🧑‍💻 김민협

#16 [FEAT] Post 관련 로직 수정 및 추가
  orury/src/main/java/org/kernel360/orury/board/comment/dto/CommentDto.java
  orury/src/main/java/org/kernel360/orury/board/comment/repository/CommentRepository.java
  orury/src/main/java/org/kernel360/orury/board/post/dto/PostDto.java
  orury/src/main/java/org/kernel360/orury/board/post/service/PostService.java
  orury/src/main/java/org/kernel360/orury/user/domain/UserAccount.java
  orury/src/main/java/org/kernel360/orury/user/dto/UserAccountDto.java
Labels: 🔥 FEATURE, 🧑‍💻 이종찬

#17 FEAT : 댓글 기능 구현 및 게시글에 일부 미구현 메서드 추가
  .idea/workspace.xml
  orury/src/main/java/org/kernel360/orury/board/comment/controller/CommentController.java
  orury/src/main/java/org/kernel360/orury/board/comment/domain/Comment.java
  orury/src/main/java/org/kernel360/orury/board/comment/dto/CommentDto.java
  orury/src/main/java/org/kernel360/orury/board/comment/repository/CommentRepository.java
  orury/src/main/java/org/kernel360/orury/board/comment/service/CommentService.java
  orury/src/main/java/org/kernel360/orury/board/post/controller/PostController.java
  orury/src/main/java/org/kernel360/orury/board/post/dto/PostDto.java
  orury/src/main/java/org/kernel360/orury/board/post/repository/PostRepository.java
  orury/src/main/java/org/kernel360/orury/board/post/service/PostService.java
  orury/src/main/resources/templates/PostDetail.html
Labels: 🔥 FEATURE

#21 REFACTOR : User Id 타입 변경으로 인한 관련 class refactor
  orury/src/main/java/org/kernel360/orury/global/security/Principal.java
  orury/src/main/java/org/kernel360/orury/global/security/SecurityConfig.java
  orury/src/main/java/org/kernel360/orury/user/domain/User.java
  orury/src/main/java/org/kernel360/orury/user/domain/UserAccount.java
  orury/src/main/java/org/kernel360/orury/user/dto/UserAccountDto.java
  orury/src/main/java/org/kernel360/orury/user/dto/UserDto.java
  orury/src/main/java/org/kernel360/orury/user/repository/UserAccountRepository.java
  orury/src/main/java/org/kernel360/orury/user/repository/UserRepository.java
  orury/src/main/java/org/kernel360/orury/user/service/UserAccountService.java
  orury/src/main/java/org/kernel360/orury/user/service/UserService.java
  orury/src/test/java/org/kernel360/orury/global/security/SecurityConfigTest.java
  orury/src/test/java/org/kernel360/orury/user/service/UserServiceTest.java
Labels: 🛠️REFACTOR

#22 REFACTOR : DB - class relations
  orury/src/main/java/org/kernel360/orury/board/post/domain/Post.java
  orury/src/main/java/org/kernel360/orury/board/post/domain/PostLike.java
  orury/src/main/java/org/kernel360/orury/board/post/dto/PostDto.java
  orury/src/main/java/org/kernel360/orury/board/post/util/isDeletedConverter.java
  orury/src/main/java/org/kernel360/orury/board/post/util/isDeletedType.java
  orury/src/main/java/org/kernel360/orury/user/dto/UserDto.java
Labels: 🛠️REFACTOR

#23 REFACTOR : fix comment - db relation 수정
  orury/src/main/java/org/kernel360/orury/board/comment/domain/Comment.java
  orury/src/main/java/org/kernel360/orury/board/comment/dto/CommentDto.java
  orury/src/main/java/org/kernel360/orury/board/post/domain/Post.java
  orury/src/main/java/org/kernel360/orury/board/post/dto/PostDto.java
  orury/src/main/java/org/kernel360/orury/global/util/isDeletedConverter.java
  orury/src/main/java/org/kernel360/orury/global/util/isDeletedType.java
Labels: 🛠️REFACTOR

#26 REFACTOR : reset security config and refactor methods in comment feature
  orury/src/main/java/org/kernel360/orury/global/security/SecurityConfig.java
Labels: ❌ FIX, 🛠️REFACTOR

#31 feat : login and signup page
  orury/build.gradle
  orury/src/main/java/org/kernel360/orury/global/controller/MainController.java
  orury/src/main/java/org/kernel360/orury/user/controller/UserController.java
  orury/src/main/java/org/kernel360/orury/user/service/UserService.java
  orury/src/main/resources/application.yml
  orury/src/main/resources/static/bootstrap.bundle.min.js
  orury/src/main/resources/static/bootstrap.css
  orury/src/main/resources/static/bootstrap.min.css
  orury/src/main/resources/static/bootstrap.min.js
  orury/src/main/resources/static/login/login.css
  orury/src/main/resources/static/my_style.css
  orury/src/main/resources/templates/CreateUserForm.html
  orury/src/main/resources/templates/board/Board.html
  orury/src/main/resources/templates/common/navbar.html
  orury/src/main/resources/templates/login/index.html
  orury/src/main/resources/templates/mypage/myPage.html
  orury/src/main/resources/templates/post/Post.html
  orury/src/main/resources/templates/post/PostDetail.html
  orury/src/main/resources/templates/user/createUserForm.html
Labels: 🔥 FEATURE
